services:
  # Local development with only infrastructure
  mongodb:
    image: mongo:6
    container_name: event-booking-mongodb-dev
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data_dev:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: event-booking-rabbitmq-dev
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq

volumes:
  mongodb_data_dev:
  rabbitmq_data_dev:
